### ISSUE TITLE
Statusbar not compiling Tracker #2412

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/statusbar_pi#13]
https://opencpn.org/flyspray/index.php?do=details&task_id=2412&order=id&sort=desc

**Comment by rgleason** [comment]
---------
Build FAILED.

"C:\Users\Rick\Documents\GitHub\statusbar_pi\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Rick\Documents\GitHub\statusbar_pi\build\statusbar_pi.vcxproj" (default target) (3) ->
(ClCompile target) ->
  C:\Users\Rick\Documents\GitHub\statusbar_pi\src\statusbar_pi.cpp(30): fatal error C1083: Cannot open include file: 'linmath.h
': No such file or directory [C:\Users\Rick\Documents\GitHub\statusbar_pi\build\statusbar_pi.vcxproj]


**Textfont.cpp**
```
#ifdef USE_ANDROID_GLES2
#include "GLES/gl2.h"
#include "linmath.h"
#include "shaders.h"
#else
 #include <GL/gl.h>
 #include <GL/glu.h>
#endif
```


**statusbar_pi.cpp**

```
#include "linmath.h"
#include "shaders.h"
#include "StatusbarUI.h"
#include "TexFont.h"
#include "statusbar_pi.h"
#include "icons.h"

```

Is linmath.h  used only for Android?
Should this be moved down to the if Android...?

```
#ifdef USE_ANDROID_GLES2    
#include "qdebug.h"
#endif

```
Was this a recent change?  I think so.

**Comment by rgleason** [comment]
I believe this April 16 version will compile and does not have linmath.h

**Comment by seandepagnier** [comment]
I will get to this soon...

**Comment by rgleason** [comment]
Sean, can you fix the linmath.h issue so it compiles for windows?  Thanks.

**Comment by seandepagnier** [comment]
does it still not compile?

**Comment by rgleason** [comment]
Sean, sorry. It does compile, just tested. Closing now.
One thing I noticed was that this is version 7 and the plugin shows as version 6
