### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by mschiff** [seandepagnier/statusbar_pi#5]
Dear developer,

I would like to make your plugin available to the users of Gentoo Linux.

Right now this is not possible because there are no releases available for your plugin.

It would be very usefull to have tagged releases, so the source for a specific version of the plugin can be downloaded. Please add a release/tag for your released versions. This makes packaging a lot easier.

Please see: [Creating Releases](https://help.github.com/articles/creating-releases/)

Thanks in advance!

**Comment by mschiff** [comment]
Could ou please also add a tag 'v0.6' for version 0.6? Thanks!

**Comment by mschiff** [comment]
Dear Sean,

what is the problem with this? Can I help inany way?

Without releases, we cannot build any packages of your software, which is a pity

**Comment by rgleason** [comment]
Releases are tag in my repository.  Perhaps this can be closed now by @mschiff ?

**Comment by mschiff** [comment]
@rgleason ok!
